# Generated by Django 5.2.3 on 2025-09-02 02:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('slider_image_1_url', models.URLField(blank=True, null=True)),
                ('slider_image_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('slider_image_2_url', models.URLField(blank=True, null=True)),
                ('slider_image_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('slider_image_3_url', models.URLField(blank=True, null=True)),
                ('grid_image_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('grid_image_1_url', models.URLField(blank=True, null=True)),
                ('grid_image_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('grid_image_2_url', models.URLField(blank=True, null=True)),
                ('redirect_url', models.URLField(default='/store')),
            ],
        ),
    ]
