# Generated by Django 5.2.3 on 2025-09-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='redirect_url',
            field=models.CharField(default='/store'),
        ),
    ]
