# Generated by Django 5.2.3 on 2025-09-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0004_campaign_sitesettings_messanger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='link',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
